export const styles = {
  container: {
    width: "100%",
    display: "flex",
    justifyContent: "space-evenly",
  },
  App: {
    width: "950px",
    height: "734px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    boxSizing: "border-box",

    background:
      'url("https://data.templateroller.com/pdf_docs_html/166/1663/166387/page_1_thumb_950.png")',
  },
  title: {
    fontSize: "62px",
    fontWeight: "700",
    margin: "0",
    color: "#e9b345",
  },
  awardTitle: {
    marginBottom: "5px",
    fontWeight: "700",
    fontSize: "30px",
    color: "#e9b345",
  },
  recognition: {
    fontSize: "38px",
    fontWeight: "700",
    color: "#e9b345",
    marginBottom: "25px",
  },
  recipientName: {
    fontSize: "60px",
    margin: "10px",
    color: "chocolate",
  },
  content: {
    textAlign: "center",
    width: "600px",
    fontSize: "30px",
    margin: "5px",
    color: "grey",
    borderTop: "1px solid burlywood",
    paddingTop: "10px",
    boxSizing: "border-box",
  },
  awardLogo: {
    width: "160px",
    height: "160px",
  },
  footer: {
    width: "600px",
    height: "180px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    boxSizing: "border-box",
    color: "#e9b345",
  },
  signatureDiv: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    fontSize: "24px",
  },
  signatureLogo: {
    width: "65px",
    height: "60px",
  },
  managerName: {
    borderTop: "1px solid burlywood",
    paddingTop: "5px",
    marginTop: "5px",
    fontWeight: "700",
  },
  date: {
    color: "#e9b345",
    textAlign: "center",
    position: "relative",
    transform: "translate(-50%)",
    left: "7%",
    fontSize: "34px",
    fontWeight: "700",
  },
  form: {
    width: "30%",
    height: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "50px",
    fontFamily: "Poppins",
  },
  inputElement: {
    width: "100%",
    height: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "5px",
  },
  label: {
    fontWeight: "500",
  },
  submitBtn: {
    width: "fit-content",
    padding: "10px 15px",
    border: "0",
    backgroundColor: "#e1e1e1",
  },
  textbox: {
    padding: "5px",
    borderRadius: "5px",
    border: "0.01rem solid #d1d1d1",
  },
  managerGap: {
    gap: "10px",
  },
};
